FROM snisioi/retele:2021

COPY ./src/*.sh ./
COPY ./src/tcp_client.py ./
COPY ./src/tcp_server.py ./
COPY /src/tcp-hj/main.py ./
COPY /src/arp-spoof/main_ARP.py ./
COPY /src/tcp-hj/router_pingARP.py ./
